### ISSUE TITLE
Not working if entries are not separated with a comment

### ISSUE THREAD

**Issue by hasn-prevas** [pfeiferj/vscode-hurl#1]
The following example from the documentation is not highlighted correctly:

```
GET https://google.fr
HTTP/* 301

GET https://google.fr
[Options]
location: true
HTTP/* 200

GET https://google.fr
HTTP/* 301
```

This is:

```
GET https://google.fr
HTTP/* 301

#

GET https://google.fr
[Options]
location: true
HTTP/* 200

#

GET https://google.fr
HTTP/* 301
```

**Comment by pfeiferj** [comment]
The tree-sitter grammar had a mistake in the http version matcher. The entry in it for HTTP/* was just HTTP. Updated tree-sitter-parser and pulled in the change. v1.0.1 is published and should show up soon in the vscode marketplace.
