### ISSUE TITLE
Incorrect Syntax Highlighting for Comment

### ISSUE THREAD

**Issue by yttriumz** [pfeiferj/vscode-hurl#16]
This is a snippet from [Hurl's doc](https://hurl.dev/docs/hurl-file.html#comments).

If there's no newline, the comment in the last line is rendered incorrectly:
![image](https://github.com/user-attachments/assets/e17704d6-8c00-4df3-9487-99ff1e0c80c2)

It looks fine if there's a new line:
![image](https://github.com/user-attachments/assets/b0215bc2-6cc4-4951-aae9-eeabbb61148b)

**Comment by pfeiferj** [comment]
Should be resolved in v1.3.4
